flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    content = TextAreaField("Content", validators=[DataRequired()])
    submit = SubmitField("Post")


class CommentForm(FlaskForm):
    content = TextAreaField("New Comment", validators=[DataRequired()])
    submit = SubmitField("Post Comment")

flask_blog/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from ..models import User


class RegistrationForm(FlaskForm):
    username = StringField(
        "Username", validators=[DataRequired(), Length(min=2, max=20)]
    )
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    confirm_password = PasswordField(
        "Confirm Password", validators=[DataRequired(), EqualTo("password")]
    )
    submit = SubmitField("Sign Up")

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError(
                "That username is taken. Please choose a diferent one."
            )

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError("That email is taken. Please choose a diferent one.")


class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    remember = BooleanField("Remember Me")
    submit = SubmitField("Login")


class UpdateAccountForm(FlaskForm):
    username = StringField(
        "Username", validators=[DataRequired(), Length(min=2, max=20)]
    )
    email = StringField("Email", validators=[DataRequired(), Email()])
    picture = FileField(
        "Update Profile Picture", validators=[FileAllowed(["jpg", "jpeg", "png"])]
    )
    submit = SubmitField("Update")

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError(
                    "That username is taken. Please choose a diferent one."
                )

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError(
                    "That email is taken. Please choose a diferent one."
                )


class RequestResetForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    submit = SubmitField("Request Password Reset")

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if not user:
            raise ValidationError(
                "There is no account with that email. You must register first."
            )


class ResetPasswordForm(FlaskForm):
    password = PasswordField("Password", validators=[DataRequired()])
    confirm_password = PasswordField(
        "Confirm Password", validators=[DataRequired(), EqualTo("password")]
    )
    submit = SubmitField("Reset Password")

flask_blog/main/routes.py
from flask import Blueprint, render_template, request
from ..models import Post

main = Blueprint("main", __name__)


@main.route("/")
@main.route("/home")
def homepage():
    page = request.args.get("page", 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=5, page=page)
    return render_template("homepage.html", title="Homepage", posts=posts)


@main.route("/about")
def about():
    return render_template("about.html", title="About")

flask_blog/posts/routes.py
from flask import Blueprint, url_for, render_template, flash, redirect, request, abort
from flask_login import current_user, login_required
from .forms import PostForm, CommentForm
from ..models import Post, Comment
from flask_blog import db

posts = Blueprint("posts", __name__)


@posts.route("/post/new", methods=("GET", "POST"))
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(
            title=form.title.data, content=form.content.data, author=current_user
        )
        db.session.add(post)
        db.session.commit()
        flash("Your post has been created!", "success")
        return redirect(url_for("main.homepage"))
    return render_template(
        "create_post.html", title="New Post", form=form, legend="New Post"
    )


@posts.route("/post/<int:post_id>", methods=("GET", "POST"))
def post(post_id):
    page = request.args.get("page", 1, type=int)
    post = Post.query.get_or_404(post_id)
    form = CommentForm()

    if form.validate_on_submit():
        comment = Comment(content=form.content.data, author=current_user, post=post)
        db.session.add(comment)
        db.session.commit()
        flash("Your comment has been posted!", "success")
        return redirect(url_for("posts.post", post_id=post.id))

    comments = (
        Comment.query.filter_by(post_id=post.id)
        .order_by(Comment.date_posted.asc())
        .paginate(per_page=5, page=page)
    )
    return render_template(
        "post.html", title=post.title, post=post, form=form, comments=comments
    )


@posts.route("/post/<int:post_id>/update", methods=("GET", "POST"))
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("Your post has been updated!", "success")
        return redirect(url_for("posts.post", post_id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    return render_template(
        "create_post.html", title="New Post", form=form, legend="Update Post"
    )


@posts.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted!", "success")
    return redirect(url_for("main.homepage"))

flask_blog/users/routes.py
from flask import Blueprint, url_for, render_template, flash, redirect, request
from flask_login import login_user, current_user, logout_user, login_required
from .forms import (
    RegistrationForm,
    LoginForm,
    UpdateAccountForm,
    RequestResetForm,
    ResetPasswordForm,
)
from ..models import User, Post
from flask_blog import db, bcrypt
from .utils import save_picture, send_reset_email

users = Blueprint("users", __name__)


@users.route("/register", methods=("GET", "POST"))
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.homepage"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=hashed_password,
        )
        db.session.add(user)
        db.session.commit()
        flash("Your account has been created!", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=("GET", "POST"))
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.homepage"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            flash("You are now logged in!", "success")
            return (
                redirect(next_page) if next_page else redirect(url_for("main.homepage"))
            )
        else:
            flash("Unsuccesful login. Please, check email and password.", "danger")
    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.homepage"))


@users.route("/account", methods=("GET", "POST"))
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_filename = save_picture(form.picture.data)
            current_user.image_file = picture_filename
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated!", "success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for("static", filename=f"profile_pics/{current_user.image_file}")
    return render_template(
        "account.html", title="Account", image_file=image_file, form=form
    )


@users.route("/user/<username>")
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get("page", 1, type=int)
    posts = (
        Post.query.order_by(Post.date_posted.desc())
        .filter_by(author=user)
        .paginate(per_page=5, page=page)
    )
    return render_template("user.html", title=user.username, user=user, posts=posts)


@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.homepage"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_reset_email(user)
            flash(
                "An email has been sent to your address with instructions to reset your password.",
                "info",
            )
            return redirect(url_for("users.login"))
    return render_template("reset_request.html", title="Reset Password", form=form)


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.homepage"))
    user = User.verify_reset_token(token)
    if not user:
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        db.session.commit()
        flash("Your password has been updated! You are now able to login.", "success")
        return redirect(url_for("users.login"))
    return render_template("reset_token.html", title="Reset Password", form=form)

flask_blog/templates/create_post.html
{% extends "layout.html" %} {% block content %}
<div class="content-section">
  <form method="post" action="#">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">{{ legend }}</legend>
      <div class="form-group">
        {{ form.title.label(class="form-control-label") }} {% if
        form.title.errors %} {{ form.title(class="form-control form-control-lg
        is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.title.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.title(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="form-group">
        {{ form.content.label(class="form-control-label") }} {% if
        form.content.errors %} {{ form.content(class="form-control
        form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.content.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.content(class="form-control form-control-lg") }} {%
        endif %}
      </div>
    </fieldset>
    <div class="form-group mt-4">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content %}

flask_blog/templates/homepage.html
{% extends "layout.html" %} {% block content %} {% for post in posts.items %}
<article class="media content-section">
  <img
    class="align-self-start rounded-circle article-img mr-16 profile-picture"
    data-toggle="modal"
    data-target="#pic{{ post.author.id }}ModalCenter"
    src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"
    alt="{{ post.author.username }} profile picture"
  />
  <div class="media-body">
    <div class="article-metadata">
      <a
        class="mr-2"
        href="{{ url_for('users.user', username=post.author.username) }}"
        >{{ post.author.username }}</a
      >
      <small class="text-muted"
        >{{ moment(post.date_posted).format('LLLL') }}</small
      >
    </div>
    <h2>
      <a
        class="article-title"
        href="{{ url_for('posts.post', post_id=post.id) }}"
        >{{ post.title }}</a
      >
    </h2>
    <p class="article-content">{{ post.content }}</p>
    {% if post.comments|count == 1 %}
    <small class="text-muted">1 Comment</small>
    {% else %}
    <small class="text-muted">{{ post.comments|count }} Comments</small>
    {% endif %}
  </div>
</article>
<!-- Profile Picture Modal -->
<div
  class="modal fade"
  id="pic{{ post.author.id }}ModalCenter"
  tabindex="-1"
  role="dialog"
  aria-labelledby="pic{{ post.author.id }}ModalCenterTitle"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <img
        src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"
        alt="{{ post.author.username }} profile picture"
      />
    </div>
  </div>
</div>
{% endfor %}
<nav>
  <ul class="pagination justify-content-center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1,
    left_current=1, right_current=2) %} {% if page_num %} {% if posts.page ==
    page_num %}
    <li class="page-item active">
      <a class="page-link" href="{{ url_for('main.homepage', page=page_num) }}">
        {{ page_num }}
        <span class="sr-only">(current)</span>
      </a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="{{ url_for('main.homepage', page=page_num) }}">
        {{ page_num }}
      </a>
    </li>
    {% endif %} {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">...</a>
    </li>
    {% endif %} {% endfor %}
  </ul>
</nav>
{% endblock content %}

flask_blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Flask Blog</title>
    {% endif %}
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='main.css') }}"
    />
    {{ moment.include_moment() }}
  </head>

  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Blog</a>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarToggle"
            aria-controls="navbarToggle"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.homepage') }}"
                >Home</a
              >
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}"
                >About</a
              >
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
              <a
                class="nav-item nav-link"
                href="{{ url_for('posts.new_post') }}"
                >New Post</a
              >
              <a class="nav-item nav-link" href="{{ url_for('users.account') }}"
                >Account</a
              >
              <a class="nav-item nav-link" href="{{ url_for('users.logout') }}"
                >Logout</a
              >
              {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}"
                >Login</a
              >
              <a
                class="nav-item nav-link"
                href="{{ url_for('users.register') }}"
                >Register</a
              >
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %} {% if
          messages %} {% for category, message in messages %}
          <div class="alert alert-{{ category }}">{{ message }}</div>
          {% endfor %} {% endif %} {% endwith %} {% block content %} {% endblock
          %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3 class="mb-3">Recent Posts</h3>
            <ul class="list-group">
              {% if recent_posts %} {% for post in recent_posts %}
              <li class="list-group-item list-group-item-light">
                <div class="row">
                  <div class="col-auto text-center">
                    <a
                      class="sidebar-profile-pic"
                      href="{{ url_for('users.user', username=post.author.username) }}"
                    >
                      <img
                        class="rounded-circle article-img mr-2"
                        style="width: 30px; height: 30px"
                        src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"
                        alt="{{ post.author.username }} profile picture"
                      />
                    </a>
                  </div>
                  <div class="col pl-0">
                    <a
                      class="article-title"
                      href="{{ url_for('posts.post', post_id=post.id) }}"
                      >{{ post.title }}</a
                    >
                  </div>
                </div>
              </li>
              {% endfor %} {% else %}
              <div class="text-center">
                No posts yet!
                <a href="{{ url_for('posts.new_post') }}">
                  Create a new one now.
                </a>
              </div>
              {% endif %}
            </ul>
            <br />
          </div>
          <div class="content-section">
            <h3 class="mb-3">New Users</h3>
            <div class="row">
              {% if recent_users %} {% for user in recent_users %}
              <div class="col text-center mb-4">
                <a
                  class="sidebar-profile-pic"
                  href="{{ url_for('users.user', username=user.username) }}"
                >
                  <img
                    class="align-self-center rounded-circle article-img m-0"
                    src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}"
                    alt="{{ user.username }} profile picture"
                  />
                </a>
              </div>
              {% endfor %} {% else %}
              <div class="col text-center mb-4">
                No users yet.
                <a href="{{ url_for('users.register') }}">
                  Be the first to register!
                </a>
              </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </main>

    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

flask_blog/templates/login.html
{% extends "layout.html" %} {% block content %}
<div class="content-section">
  <form method="post" action="#">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Log In</legend>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }} {% if
        form.email.errors %} {{ form.email(class="form-control form-control-lg
        is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.email(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="form-group">
        {{ form.password.label(class="form-control-label") }} {% if
        form.password.errors %} {{ form.password(class="form-control
        form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.password(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="form-check">
        {{ form.remember(class="form-check-input") }} {{
        form.remember.label(class="form-check-label") }}
      </div>
    </fieldset>
    <div class="form-group mt-4">
      {{ form.submit(class="btn btn-outline-info") }}
      <small class="text-muted ml-2">
        <a href="{{ url_for('users.reset_request') }}">Forgot Your Password?</a>
      </small>
    </div>
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted">
    Need an Account?
    <a class="ml-2" href="{{ url_for('users.register') }}">Sign In</a>
  </small>
</div>
{% endblock %}

flask_blog/templates/post.html
{% extends "layout.html" %} {% block content %}
<article class="media content-section">
  <img
    class="align-self-start rounded-circle article-img mr-16 profile-picture"
    src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"
    alt="{{ post.author.username }} profile picture"
    data-toggle="modal"
    data-target="#pic{{ post.author.id }}ModalCenter"
  />
  <div class="media-body">
    <div class="article-metadata">
      <a
        class="mr-2"
        href="{{ url_for('users.user', username=post.author.username) }}"
        >{{ post.author.username }}</a
      >
      <small class="text-muted"
        >{{ moment(post.date_posted).format('LLLL') }}</small
      >
      {% if post.author == current_user %}
      <div>
        <a
          class="btn btn-secondary btn-sm mt-1 mb-1"
          href="{{ url_for('posts.update_post', post_id=post.id) }}"
          >Update</a
        >
        <button
          type="button"
          class="btn btn-danger btn-sm m-1"
          data-toggle="modal"
          data-target="#deleteModal"
        >
          Delete
        </button>
      </div>
      {% endif %}
    </div>
    <h2 class="article-title">{{ post.title }}</h2>
    <p class="article-content mb-4">{{ post.content }}</p>
    {% for comment in comments.items %}
    <div class="media mb-4">
      <img
        class="align-self-start rounded-circle article-img mr-16 profile-picture"
        src="{{ url_for('static', filename='profile_pics/' + comment.author.image_file) }}"
        alt="{{ post.author.username }} profile picture"
        data-toggle="modal"
        data-target="#pic{{ comment.author.id }}ModalCenter"
      />
      <div class="media-body">
        <div class="article-metadata">
          <a
            class="mr-2"
            href="{{ url_for('users.user', username=comment.author.username) }}"
            >{{ comment.author.username }}</a
          >
          <small class="text-muted"
            >{{ moment(comment.date_posted).format('LLLL') }}</small
          >
        </div>
        <p class="article-content">{{ comment.content }}</p>
      </div>
    </div>
    {% endfor %}
    <form method="post" action="#">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <div class="form-group">
          {{ form.content.label(class="form-control-label") }} {% if
          form.content.errors %} {{ form.content(class="form-control
          form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.content.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.content(class="form-control form-control-lg") }} {%
          endif %}
        </div>
      </fieldset>
      <div class="form-group mt-4">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>
    <nav>
      <ul class="pagination justify-content-center">
        {% for page_num in comments.iter_pages(left_edge=1, right_edge=1,
        left_current=1, right_current=2) %} {% if page_num %} {% if
        comments.page == page_num %}
        <li class="page-item active">
          <a
            class="page-link"
            href="{{ url_for('posts.post', page=page_num, post_id=post.id) }}"
          >
            {{ page_num }}
            <span class="sr-only">(current)</span>
          </a>
        </li>
        {% else %}
        <li class="page-item">
          <a
            class="page-link"
            href="{{ url_for('posts.post', page=page_num, post_id=post.id) }}"
          >
            {{ page_num }}
          </a>
        </li>
        {% endif %} {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1">...</a>
        </li>
        {% endif %} {% endfor %}
      </ul>
    </nav>
  </div>
</article>
<!-- Profile Picture Modal -->
<div
  class="modal fade"
  id="pic{{ post.author.id }}ModalCenter"
  tabindex="-1"
  role="dialog"
  aria-labelledby="pic{{ post.author.id }}ModalCenterTitle"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <img
        src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"
        alt="{{ post.author.username }} profile picture"
      />
    </div>
  </div>
</div>
<!-- Delete Modal -->
<div
  class="modal fade"
  id="deleteModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="deleteModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Are You Sure?</h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Close
        </button>
        <form
          action="{{ url_for('posts.delete_post', post_id=post.id) }}"
          method="POST"
        >
          <input class="btn btn-danger" type="submit" value="Delete" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

flask_blog/templates/user.html
{% extends "layout.html" %} {% block content %}
<div class="content-section">
  <div class="media">
    <img
      class="rounded-circle account-img profile-picture"
      data-toggle="modal"
      data-target="#pic{{ user.id }}ModalCenter"
      src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}"
      alt="{{ user.username }} profile picture"
    />
    <div class="media-body">
      <h2 class="account-heading">{{ user.username }}</h2>
      <p class="text-secondary">{{ user.email }}</p>
      <p class="text-secondary">
        Member since {{ moment(user.date_signed_in).format('LL') }}
      </p>
    </div>
  </div>
</div>
<!-- Profile Picture Modal -->
<div
  class="modal fade"
  id="pic{{ user.id }}ModalCenter"
  tabindex="-1"
  role="dialog"
  aria-labelledby="pic{{ user.id }}ModalCenterTitle"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <img
        src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}"
        alt="{{ user.username }} profile picture"
      />
    </div>
  </div>
</div>
{% for post in posts.items %}
<article class="media content-section">
  <div class="media-body">
    <div class="article-metadata">
      <a
        class="mr-2"
        href="{{ url_for('users.user', username=post.author.username) }}"
        >{{ post.author.username }}</a
      >
      <small class="text-muted"
        >{{ moment(post.date_posted).format('LLLL') }}</small
      >
    </div>
    <h2>
      <a
        class="article-title"
        href="{{ url_for('posts.post', post_id=post.id) }}"
        >{{ post.title }}</a
      >
    </h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
{% endfor %}
<nav>
  <ul class="pagination justify-content-center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1,
    left_current=1, right_current=2) %} {% if page_num %} {% if posts.page ==
    page_num %}
    <li class="page-item active">
      <a
        class="page-link"
        href="{{ url_for('users.user', username=user.username, page=page_num) }}"
      >
        {{ page_num }}
        <span class="sr-only">(current)</span>
      </a>
    </li>
    {% else %}
    <li class="page-item">
      <a
        class="page-link"
        href="{{ url_for('users.user', username=user.username, page=page_num) }}"
      >
        {{ page_num }}
      </a>
    </li>
    {% endif %} {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">...</a>
    </li>
    {% endif %} {% endfor %}
  </ul>
</nav>
{% endblock content %}